// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/risentveber/example-di-go/services/clients"
	"github.com/risentveber/example-di-go/services/orders"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func BuildAppCompileTime() (*App, error) {
	listener, err := NewListener()
	if err != nil {
		return nil, err
	}
	db, err := NewDB()
	if err != nil {
		return nil, err
	}
	sqlRepository := clients.NewRepository(db)
	plainService := clients.NewService(sqlRepository)
	handlersHTTP := clients.NewHTTPProvider(plainService)
	ordersSQLRepository := orders.NewRepository(db)
	ordersPlainService := orders.NewService(ordersSQLRepository)
	ordersHandlersHTTP := orders.NewHTTPProvider(ordersPlainService)
	handler := NewRouter(handlersHTTP, ordersHandlersHTTP)
	app := NewApp(listener, handler)
	return app, nil
}
